OPENAI_API_KEY = "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"
[theme]
base="dark"
primaryColor="#00C9A7"
font="sans serif"
